spring.application.name=spring-boot-apache-activemq
spring.activemq.broker-url= tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin


management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4317
logging.pattern.level=%5p [traceId=%X{traceId}]

